export const data = [
    {
        state: "작성중",
        date : "2024.04.01",
        time : "09:00",
        shelter : "요양병원", 
        region : "서울시 양천구",
        rating : "1등급",
        size : "대형",
        class : "고급형",
    },
    {
        state: "신청완료",
        date : "2024.04.02",
        time : "09:00",
        shelter : "요양원", 
        region : "서울시 양천구",
        rating : "신설기관",
        size : "소형",
        class : "일반형",
    },
    {
        state: "작성중",
        date : "2024.04.04",
        time : "09:00",
        shelter : "주야간보호", 
        region : "서울시 양천구",
        rating : "3등급",
        size : "중형",
        class : "일반형",
     },
    {
        state: "작성중",
        date : "2022.01.01",
        time : "09:00",
        shelter : "방문시설", 
        region : "서울시 강서구",
        rating : "1등급",
        size : "대형",
        class : "실속형",
    },
  ]